modules:
  - name: 'gl_app/viewer-main'
  - name: 'gl_app/editor-main'

paths:
  'async': 'async.min'
  'jquery': 'jquery-1.7.2.min'
  'jquery-ui': 'jquery-ui-1.8.21.custom.min'
  'gl-matrix': 'gl-matrix-min'
  'gl-matrix-ext': 'gl_app/gl-matrix-ext'

shim:
  'jquery.debouncedresize': ['jquery']
  'jquery-ui': ['jquery']
  'gl-matrix-ext': ['gl-matrix']
  'loader': ['base']