paths:
  'async': 'async.min'
  'jquery': 'jquery-1.7.2.min'
  'jquery-ui': 'jquery-ui-1.8.21.custom.min'
  'gl-matrix': 'gl-matrix-min'

shim:
  'jquery.debouncedresize': ['jquery']
  'jquery-ui': ['jquery']
  'gl-matrix-ext': ['gl-matrix']
  'loader': ['base']