modules:
  - name: 'gl_app/viewer-main'
  - name: 'gl_app/editor-main'

paths:
  'async': 'async.min'
  'jquery': 'jquery-1.11.1.min'
  'jquery-ui': 'jquery-ui-1.11.1.min'
  'jquery.hotkeys': 'jquery.hotkeys'
  'jquery.datatables': 'jquery.dataTables.min'
  'jquery.datatables.bootstrap': 'dataTables.bootstrap'
  'jquery.datatables.tabletools': 'dataTables.tableTools.min'
  'gl-matrix': 'gl-matrix-min'
  'gl-matrix-ext': 'gl_app/gl-matrix-ext'
  'bootstrap': 'bootstrap'
  'bootbox': 'bootbox.min'
  'slick': 'slick.min'

shim:
  'jquery.debouncedresize': ['jquery']
  'jquery-ui': ['jquery']
  'jquery.console': ['jquery']
  'jquery.hotkeys': ['jquery']
  'jquery.datatables': ['jquery']
  'jquery.datatables.bootstrap': ['jquery.datatables']
  'jquery.datatables.tabletools': ['jquery.datatables']
  'bootstrap': ['jquery']
  'bootbox': ['bootstrap']
  'gl-matrix-ext': ['gl-matrix']
  'loader': ['base']
  'base': ['jquery']
  'slick': ['jquery']