modules:
  - name: 'edit'
  - name: 'view'
paths:
  - 'async': 'async.min'
  - 'jquery': 'jquery-ui/js/jquery-1.7.2.min'
  - 'jquery-ui': 'jquery-ui/js/jquery-ui-1.8.21.custom.min'
  - 'gl-matrix': 'gl-matrix-min'
  - 'game-shim': 'game-shim'

shim:
  - 'jquery.debouncedresize': ['jquery']
  - 'jquery-ui': ['jquery']
  - 'gl-matrix-ext': ['gl-matrix']
  - 'loader': ['base']